-- Academic App Database Schema
-- Run this script in your PostgreSQL database to create all the necessary tables.

CREATE TABLE admins ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL DEFAULT 'admin', phone VARCHAR(20) DEFAULT '', avatar_url TEXT DEFAULT '', is_active BOOLEAN DEFAULT true, id_no VARCHAR(50) DEFAULT '', id_card_url TEXT DEFAULT '', joining_date DATE, permissions TEXT[] DEFAULT '{}', gender VARCHAR(50), address TEXT, state VARCHAR(100), district VARCHAR(100), pincode VARCHAR(20), aadhar_no VARCHAR(50), aadhar_card_url TEXT, signature_url TEXT, login_time_type VARCHAR(50) DEFAULT 'Always', login_time VARCHAR(50), logout_time VARCHAR(50), login_expire_date DATE, device_permission_count INTEGER DEFAULT 1, last_login_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE segments ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL UNIQUE, menus TEXT[] DEFAULT '{}', description TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE institutions ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, code VARCHAR(100) UNIQUE, segment_id UUID REFERENCES segments(id) ON DELETE SET NULL, affiliated_to VARCHAR(255), affiliation_code VARCHAR(100), contact_person VARCHAR(255) NOT NULL, mobile_no VARCHAR(20), email_id VARCHAR(255), address TEXT, state VARCHAR(100) NOT NULL, district VARCHAR(100) NOT NULL, pincode VARCHAR(20), principal_name VARCHAR(255), principal_gender VARCHAR(50), principal_sign TEXT, principal_photo TEXT, director_name VARCHAR(255), director_gender VARCHAR(50), director_sign TEXT, director_photo TEXT, status VARCHAR(50) NOT NULL DEFAULT 'Active', assigned_to UUID REFERENCES admins(id) ON DELETE SET NULL, password_hash VARCHAR(255) DEFAULT '', plain_password VARCHAR(255) DEFAULT '', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE applications ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), application_no VARCHAR(50) NOT NULL UNIQUE, institution_id UUID REFERENCES institutions(id) ON DELETE CASCADE, school_name VARCHAR(255), contact_person VARCHAR(255), status VARCHAR(50) NOT NULL DEFAULT 'Applied', enquiry_status VARCHAR(100), plan_id UUID, promo_code VARCHAR(255), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE plans ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), segment_id UUID REFERENCES segments(id) ON DELETE CASCADE, segment VARCHAR(255), applied_by TEXT NOT NULL, plan_for TEXT NOT NULL DEFAULT 'All User', plan_name TEXT NOT NULL, description TEXT, no_of_students INTEGER, students_fee_relaxation INTEGER, additional_charge_per_student NUMERIC(10,2), first_billing_duration INTEGER, renewal_billing_duration INTEGER, renewal_pre_bill_generate_days INTEGER, renewal_payment_relaxation NUMERIC(5,2), status TEXT DEFAULT 'Active', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE plan_billing_items ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), plan_id UUID NOT NULL REFERENCES plans(id) ON DELETE CASCADE, billing_type TEXT NOT NULL CHECK (billing_type IN ('first', 'renewal')), serial_no INTEGER NOT NULL, item_description TEXT NOT NULL DEFAULT '', price NUMERIC(10,2) NOT NULL DEFAULT 0, tax_percentage NUMERIC(5,2) NOT NULL DEFAULT 0, tax_price NUMERIC(10,2) NOT NULL DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE promo_codes ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(50) UNIQUE NOT NULL, description TEXT DEFAULT '', segment_id UUID REFERENCES segments(id) ON DELETE SET NULL, segment VARCHAR(255), applicable_by VARCHAR(255) DEFAULT '', applicable_one BOOLEAN DEFAULT false, discount_name VARCHAR(255) DEFAULT '', discount_type VARCHAR(10) NOT NULL DEFAULT 'Percentage' CHECK (discount_type IN ('Percentage', 'Fixed')), discount_value NUMERIC(10,2) NOT NULL DEFAULT 0, max_uses INTEGER NOT NULL DEFAULT 0, current_uses INTEGER NOT NULL DEFAULT 0, start_date DATE, has_expiry BOOLEAN DEFAULT false, expiry_date DATE, status TEXT DEFAULT 'Active', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE bills ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), institution_id UUID REFERENCES institutions(id) ON DELETE CASCADE, plan_id UUID REFERENCES plans(id) ON DELETE SET NULL, school_name VARCHAR(255), plan_name VARCHAR(255), payment_mode VARCHAR(50) NOT NULL, payment_date DATE NOT NULL DEFAULT CURRENT_DATE, amount NUMERIC(10,2) NOT NULL DEFAULT 0, transaction_id VARCHAR(100), status VARCHAR(50) NOT NULL DEFAULT 'Paid', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE requests ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), institution_id UUID REFERENCES institutions(id) ON DELETE CASCADE, plan_id UUID REFERENCES plans(id) ON DELETE SET NULL, school_name VARCHAR(255), plan_name VARCHAR(255), payment_mode VARCHAR(50) NOT NULL, transaction_id VARCHAR(100), amount NUMERIC(10,2) NOT NULL DEFAULT 0, transaction_amount NUMERIC(10,2) DEFAULT 0, status VARCHAR(50) NOT NULL DEFAULT 'Pending', screenshots JSONB NOT NULL DEFAULT '[]'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE ticket_categories ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) UNIQUE NOT NULL, description TEXT DEFAULT '', parent_category VARCHAR(255) DEFAULT '', segment_id UUID REFERENCES segments(id) ON DELETE SET NULL, segment VARCHAR(255), low_timeline VARCHAR(255) DEFAULT '', medium_timeline VARCHAR(255) DEFAULT '', high_timeline VARCHAR(255) DEFAULT '', is_deleted BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE tickets ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), ticket_no VARCHAR(50) UNIQUE NOT NULL, assigned_to_id UUID REFERENCES admins(id) ON DELETE SET NULL, assigned_to VARCHAR(255), institution_id UUID REFERENCES institutions(id) ON DELETE CASCADE, school_name VARCHAR(255), category_id UUID REFERENCES ticket_categories(id) ON DELETE SET NULL, ticket_category VARCHAR(255), segment VARCHAR(255), sub_category VARCHAR(255) DEFAULT '', priority VARCHAR(50) DEFAULT 'Low', complainer_name VARCHAR(255) DEFAULT '', complainer_mobile VARCHAR(50) DEFAULT '', description TEXT DEFAULT '', image_attachment VARCHAR(255) DEFAULT '', status VARCHAR(50) NOT NULL DEFAULT 'Pending', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE lead_statuses ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(100) UNIQUE NOT NULL, text_color VARCHAR(50) DEFAULT '', bg_color VARCHAR(50) DEFAULT '', show_on_bdm BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE leads ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), lead_source VARCHAR(150) NOT NULL, mobile_no VARCHAR(50) NOT NULL, email_id VARCHAR(150) DEFAULT '', contact_person VARCHAR(255) DEFAULT '', institution_id UUID REFERENCES institutions(id) ON DELETE SET NULL, institution_name VARCHAR(255) NOT NULL, state VARCHAR(100) DEFAULT '', district VARCHAR(100) DEFAULT '', no_of_students INTEGER DEFAULT 0, status_id UUID REFERENCES lead_statuses(id) ON DELETE SET NULL, assigned_to_id UUID REFERENCES admins(id) ON DELETE SET NULL, assigned_to VARCHAR(255), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE lead_history ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), lead_id UUID REFERENCES leads(id) ON DELETE CASCADE, communication_option VARCHAR(50) NOT NULL, call_duration VARCHAR(100) DEFAULT '', remarks TEXT DEFAULT '', follow_up_date DATE, status_id UUID REFERENCES lead_statuses(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE distributors ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), dist_id VARCHAR(100) UNIQUE NOT NULL, joining_date DATE, name VARCHAR(255) NOT NULL, mobile_no VARCHAR(50) NOT NULL, email VARCHAR(255) DEFAULT '', gender VARCHAR(50) DEFAULT '', photo_url TEXT DEFAULT '', username VARCHAR(100) UNIQUE NOT NULL, password_hash VARCHAR(255) DEFAULT '', address TEXT DEFAULT '', state VARCHAR(100) DEFAULT '', district VARCHAR(100) DEFAULT '', pincode VARCHAR(20) DEFAULT '', aadhar_no VARCHAR(50) DEFAULT '', aadhar_url TEXT DEFAULT '', signature_url TEXT DEFAULT '', agreement_url TEXT DEFAULT '', commission_in VARCHAR(50) DEFAULT '', commission_value NUMERIC(10,2) DEFAULT 0, commission_type VARCHAR(50) DEFAULT '', assign_area TEXT DEFAULT '', account_holder_name VARCHAR(255) DEFAULT '', account_number VARCHAR(100) DEFAULT '', ifsc_code VARCHAR(50) DEFAULT '', bank_name VARCHAR(255) DEFAULT '', pan_no VARCHAR(20) DEFAULT '', upi_id VARCHAR(255) DEFAULT '', qr_code_url TEXT DEFAULT '', commission_total NUMERIC(10,2) DEFAULT 0, status VARCHAR(50) DEFAULT 'Active', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE distributor_payments ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), distributor_id UUID REFERENCES distributors(id) ON DELETE CASCADE, amount NUMERIC(10,2) NOT NULL DEFAULT 0, payment_date DATE NOT NULL DEFAULT CURRENT_DATE, payment_mode VARCHAR(100) DEFAULT '', transaction_id VARCHAR(100) DEFAULT '', status VARCHAR(50) DEFAULT 'Paid', remarks TEXT DEFAULT '', created_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE referrals ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), referral_by_admin UUID REFERENCES admins(id) ON DELETE CASCADE, referral_by_distributor UUID REFERENCES distributors(id) ON DELETE CASCADE, referral_to_institution UUID REFERENCES institutions(id) ON DELETE CASCADE, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, mobile_no VARCHAR(50) NOT NULL, status VARCHAR(50) DEFAULT 'Pending', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE income_categories ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL UNIQUE, description TEXT DEFAULT '', category_type VARCHAR(50) DEFAULT 'Income', created_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE income_parties ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, mobile_no VARCHAR(50) DEFAULT '', email VARCHAR(255) DEFAULT '', party_category VARCHAR(50) DEFAULT 'Income', contact_person VARCHAR(255) DEFAULT '', amount NUMERIC(10,2) DEFAULT 0, gst_no VARCHAR(100) DEFAULT '', address TEXT DEFAULT '', created_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE income_sessions ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(100) NOT NULL UNIQUE, created_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE income_records ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), trans_id VARCHAR(100) DEFAULT '', category_id UUID REFERENCES income_categories(id) ON DELETE SET NULL, income_category VARCHAR(255), amount NUMERIC(10,2) DEFAULT 0, payment_mode VARCHAR(100) DEFAULT '', received_date DATE NOT NULL DEFAULT CURRENT_DATE, party_id UUID REFERENCES income_parties(id) ON DELETE SET NULL, received_from VARCHAR(255), payment_account VARCHAR(100) DEFAULT '', reference_no VARCHAR(100) DEFAULT '', session_id UUID REFERENCES income_sessions(id) ON DELETE SET NULL, photo_url TEXT DEFAULT '', status VARCHAR(50) DEFAULT 'Paid', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE expense_records ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), trans_id VARCHAR(100) DEFAULT '', category_id UUID REFERENCES income_categories(id) ON DELETE SET NULL, amount NUMERIC(10,2) DEFAULT 0, payment_mode VARCHAR(100) DEFAULT '', expense_date DATE NOT NULL DEFAULT CURRENT_DATE, paid_by_id UUID REFERENCES admins(id) ON DELETE SET NULL, paid_by VARCHAR(255), paid_to_id UUID REFERENCES income_parties(id) ON DELETE SET NULL, paid_to VARCHAR(255), payment_account VARCHAR(100) DEFAULT '', received_by VARCHAR(255) DEFAULT '', approved_by_id UUID REFERENCES admins(id) ON DELETE SET NULL, approved_by VARCHAR(255), photo_url TEXT DEFAULT '', status VARCHAR(50) DEFAULT 'Paid', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE products ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, description TEXT NOT NULL, images TEXT[] DEFAULT '{}', mrp_price NUMERIC(10,2) NOT NULL, sell_price NUMERIC(10,2) NOT NULL, colors TEXT[] DEFAULT '{}', sizes TEXT[] DEFAULT '{}', features TEXT[] DEFAULT '{}', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE product_enquiries ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), institution_id UUID REFERENCES institutions(id) ON DELETE CASCADE, school_name VARCHAR(255), product_id UUID REFERENCES products(id) ON DELETE CASCADE, product_name VARCHAR(255), quantity INTEGER NOT NULL, enquiry_date DATE NOT NULL DEFAULT CURRENT_DATE, name VARCHAR(255), mobile_no VARCHAR(50), address TEXT, created_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE product_dispatches ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), institution_id UUID REFERENCES institutions(id) ON DELETE CASCADE, school_name VARCHAR(255), product_id UUID REFERENCES products(id) ON DELETE CASCADE, product_name VARCHAR(255), quantity INTEGER NOT NULL, size VARCHAR(50) DEFAULT '', product_as VARCHAR(50) DEFAULT 'Gift', dispatch_date DATE NOT NULL DEFAULT CURRENT_DATE, status VARCHAR(50) DEFAULT 'Payment Pending', price NUMERIC(10,2) DEFAULT 0, tax_percent NUMERIC(5,2) DEFAULT 0, total_amount NUMERIC(10,2) DEFAULT 0, courier_name VARCHAR(255) DEFAULT '', courier_id VARCHAR(255) DEFAULT '', name VARCHAR(255), mobile_no VARCHAR(50), address TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE sms_orders ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), institution_id UUID REFERENCES institutions(id) ON DELETE CASCADE, school_name VARCHAR(255), mobile_no VARCHAR(50), email VARCHAR(255), sms_quantity INTEGER NOT NULL, amount NUMERIC(10,2) NOT NULL, status VARCHAR(50) NOT NULL DEFAULT 'New Order', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE sms_templates ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), template_name VARCHAR(255) NOT NULL, message_content TEXT NOT NULL, status VARCHAR(50) NOT NULL DEFAULT 'Pending', created_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE sms_template_requests ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), assigned_to_id UUID REFERENCES admins(id) ON DELETE SET NULL, assigned_to VARCHAR(255), institution_id UUID REFERENCES institutions(id) ON DELETE CASCADE, school_name VARCHAR(255), contact_person VARCHAR(255), mobile_no VARCHAR(50), remarks TEXT DEFAULT '', status VARCHAR(50) DEFAULT 'Pending', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE sms_template_request_history ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), request_id UUID REFERENCES sms_template_requests(id) ON DELETE CASCADE, communication_option VARCHAR(50) DEFAULT 'Call', call_duration VARCHAR(100) DEFAULT '', remarks TEXT DEFAULT '', follow_up_date DATE, status VARCHAR(50) DEFAULT '', lead_source VARCHAR(100) DEFAULT 'Offline Meeting', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE device_brands ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL UNIQUE );
CREATE TABLE device_types ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL UNIQUE );
CREATE TABLE device_plans ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, duration_type VARCHAR(50) DEFAULT 'Days', duration INTEGER NOT NULL, amount NUMERIC(10,2) NOT NULL, tax_percent NUMERIC(5,2) DEFAULT 18, total_amount NUMERIC(10,2) NOT NULL, status VARCHAR(50) DEFAULT 'Active', brand_id UUID REFERENCES device_brands(id) ON DELETE SET NULL, type_id UUID REFERENCES device_types(id) ON DELETE SET NULL, device_name VARCHAR(255) DEFAULT 'Device 1', imei_no VARCHAR(100) DEFAULT '1234567890', description TEXT DEFAULT '', plan_description TEXT DEFAULT '', image_url TEXT DEFAULT '', created_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE device_recharge_requests ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), institution_id UUID REFERENCES institutions(id) ON DELETE CASCADE, school_name VARCHAR(255), device_plan_id UUID REFERENCES device_plans(id) ON DELETE SET NULL, device_name VARCHAR(255), device_type VARCHAR(100), image_url TEXT DEFAULT '', plan_duration VARCHAR(100) DEFAULT '30 Days', amount NUMERIC(10,2) NOT NULL, payment_reference VARCHAR(255) DEFAULT '', description TEXT DEFAULT 'Lorem Ipsum', sim_imei_no VARCHAR(100) DEFAULT '1234567890', sim_no VARCHAR(50) DEFAULT '9999999999', tax_percent NUMERIC(5,2) DEFAULT 18, total_amount NUMERIC(10,2) NOT NULL, start_date DATE, end_date DATE, verified BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE states_districts ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), state_name VARCHAR(255) UNIQUE NOT NULL, districts TEXT[] DEFAULT '{}', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE queries ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, mobile_no VARCHAR(50) NOT NULL, email VARCHAR(255) NOT NULL DEFAULT '', query_for VARCHAR(255) NOT NULL DEFAULT '', message TEXT NOT NULL DEFAULT '', response_message TEXT DEFAULT '', status VARCHAR(50) DEFAULT 'Pending', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW() );
CREATE TABLE messages ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sender VARCHAR(255) NOT NULL, receiver VARCHAR(255) NOT NULL, message TEXT NOT NULL DEFAULT '', is_read BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ DEFAULT NOW() );
